[project]
name = "tvdatafeed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.7",
    "pandas>=2.3.2",
    "requests>=2.32.5",
    "websocket-client>=1.8.0",
]
